version: 2
jobs:
  test:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - run:
          name: Upgrade npm
          command: sudo npm i --no-progress -g npm@6.9.0
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm i --no-progress
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm test

  deploy-dev:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - run:
          name: Upgrade npm
          command: sudo npm i --no-progress -g npm@6.9.0
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm i --no-progress
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm test
      - run: npm run build:prod:relative
      - add_ssh_keys:
          fingerprints:
            - "ef:f5:a9:bb:63:8d:9e:1d:ce:ab:1b:12:8d:a3:db:22"
      - deploy:
          command: npm run deploy:dev

  deploy-prod:
    docker:
      - image: circleci/node:10.15.3
    working_directory: ~/repo
    steps:
      - run:
          name: Upgrade npm
          command: sudo npm i --no-progress -g npm@6.9.0
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package-lock.json" }}
            - v1-dependencies-
      - run: npm i --no-progress
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package-lock.json" }}
      - run: npm run lint
      - run: npm test
      - run: npm run build:prod
      - add_ssh_keys:
          fingerprints:
            - "ef:f5:a9:bb:63:8d:9e:1d:ce:ab:1b:12:8d:a3:db:22"
      - deploy:
          command: npm run deploy:prod

workflows:
  version: 2
  build-deploy:
    jobs:
      - test:
          filters:
            branches:
              only: /^greenkeeper\/.*$/
      - deploy-dev:
          filters:
            branches:
              only: /dev-.*/
      - deploy-prod:
          filters:
            branches:
              only: master
